name: grupo_digital_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.4.0
  fluttertoast: ^9.0.0
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.8.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - .env
